framework:
    default_locale: 'fr'
    translator:
        default_path: '%kernel.project_dir%/translations'
        providers:
            # Uncomment the following line if you want to load translations from a database
            # app: App\Translation\DoctrineTranslationProvider
