# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
# config/services.yaml
parameters: {}

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\:
    resource: '../src/'

  App\Service\StripeCheckout:
    arguments:
      $secretKey: '%env(STRIPE_SECRET_KEY)%'

  # Quand un service demande ProductLookup, on retourne le ProductRepository
  App\Port\ProductLookup: '@App\Repository\ProductRepository'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
